exports.studentsListPage = function(slist, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Student Management</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Students List 
                        <a href="/alunos/registo" class="w3-button w3-round-xxlarge">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Name</th><th>GitLink</th>
                            <th>Actions</th>
                        </tr>
                `
    for(let i=0; i < slist.length ; i++){
        pagHTML += `
                <tr>
                    <td>${slist[i].id}</td>
                    <td>
                        <a href="/alunos/${slist[i].id}">${slist[i].nome}</a>
                    </td>
                    <td>
                        <a href="${slist[i].gitlink}">Github</a>
                    </td>
                    <td>[<a href="/alunos/${slist[i].id}/editar">Edit</a>]   [<a href="/alunos/${slist[i].id}/remover">Delete</a>]</td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by RPCW2023 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

// ---------------Student's Page--------------------------------
exports.studentPage = ( aluno, d ) => {
    pagHTML = `
    <html>
    <head>
        <title>Aluno: ${aluno.id}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Aluno ${aluno.id}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Nome: </b> ${aluno.nome}</li>
                    <li><b>Número: </b> ${aluno.id}</li>
                    <li><b>Git (link): </b> <a href="${aluno.gitlink}">${aluno.gitlink}</a></li>
                </ul>
            </div>

            <div class="w3-container">
                <table class="w3-table-all">
                <tr>
                    <th>TPC1</th><th>TPC2</th><th>TPC3</th><th>TPC4</th><th>TPC5</th>
                    <th>TPC6</th><th>TPC7</th><th>TPC8</th>
                </tr>
                <tr>
                    <td>${aluno.tpc1 ? 1 : 0}</td>
                    <td>${aluno.tpc2 ? 1 : 0}</td>
                    <td>${aluno.tpc3 ? 1 : 0}</td>
                    <td>${aluno.tpc4 ? 1 : 0}</td>
                    <td>${aluno.tpc5 ? 1 : 0}</td>
                    <td>${aluno.tpc6 ? 1 : 0}</td>
                    <td>${aluno.tpc7 ? 1 : 0}</td>
                    <td>${aluno.tpc8 ? 1 : 0}</td>
                </tr>
                </table>
            </div>
                `

    pagHTML += `        <footer class="w3-container w3-teal">
                <address>Gerado por galuno::RPCW2022 em ${d} - [<a href="/">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}

// ---------------Student's Register Page--------------------------------
exports.studentFormPage = ( d ) => {
    var pagHTML = `
        <!DOCTYPE html>
        <html>
            <head>
                <meta charset="UTF-8"/>
                <link rel="icon" href="favicon.png"/>
                <link rel="stylesheet" href="w3.css"/>
                <title>Registar aluno</title>
            </head>
            <body>
                <div class="w3-card-4">
                    <header class="w3-container w3-purple">
                        <h2>Registar aluno</h2>
                    </header>
                
                    <form class="w3-container" method="POST">
                        <label for="name">Name</label>
                        <input class="w3-input w3-round" type="text" name="nome">
                    
                        <label for="id">Número</label>
                        <input class="w3-input w3-round" type="text" name="id">
                    
                        <label for="gitlink">Git (link)</label>
                        <input class="w3-input w3-round" type="text" name="gitlink">
                        
                        <fieldset>
                            <legend>TPC's Realizados</legend>

    `
    for(let i = 1; i <= 8; i++){
        pagHTML += `
                        
                            <label for="tpc${i}">TPC${i}</label>
                            <input class="w3-check" type="checkbox" name="tpc${i}" value="1" >
                       
        `
    }

    
    pagHTML += `            </fieldset>
                        <br/>
                        <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                    </form>
    
                    <footer class="w3-container w3-purple">
                        <h5>Generated by RPCW2023 in ${d} - [<a href="/">Return</a>]</h5>
                    </footer>
                
                </div>
                `
        return pagHTML
    }
    
    // ---------------Student's Confirmation Page--------------------------------

    exports.alunoConfirmPage = function( person, d ){
        return `
        <html>
        <head>
            <title>Aluno: ${person.nome}</title>
            <meta charset="utf-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                    <h1>${person.nome}</h1>
                </header>
    
                <div class="w3-container">
                    <ul class="w3-ul w3-card-4" style="width:50%">
                        <li><b>Name: </b> ${person.nome}</li>
                        <li><b>Number: </b> ${person.id}</li>
                    </ul>
                </div>
    
                <footer class="w3-container w3-teal">
                    <address>Generated by RPCW2023 in ${d} - [<a href="/">Return</a>]</address>
                </footer>
            </div>
        </body>
        </html>
        `
    }